apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: metallb-config
data:
  config: |
    address-pools:
    - name: lb-mylab-pool
      protocol: layer2
      addresses:
      - 192.168.2.80-192.168.2.99